/* Generated By:JavaCC: Do not edit this line. RTFParserConstants.java */
package org.apache.harmony.x.swing.text.rtf;

public interface RTFParserConstants {

  int EOF = 0;
  int BACKSLASH = 1;
  int OPEN_BRACE = 5;
  int CLOSE_BRACE = 6;
  int TEXT = 7;
  int RTF = 12;
  int FONTTBL = 13;
  int STYLESHEET = 14;
  int INFO = 15;
  int B = 16;
  int I = 17;
  int UL = 18;
  int IGNORED_DESTINATION = 19;
  int CONTROL_WORD = 20;
  int CONTROL_SYMBOL = 21;
  int PARAM = 22;

  int IN_CONTROL = 0;
  int DEFAULT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"\\\\\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"{\"",
    "\"}\"",
    "<TEXT>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"rtf\"",
    "\"fonttbl\"",
    "\"stylesheet\"",
    "\"info\"",
    "\"b\"",
    "\"i\"",
    "\"ul\"",
    "\"*\"",
    "<CONTROL_WORD>",
    "<CONTROL_SYMBOL>",
    "<PARAM>",
    "<token of kind 23>",
  };

}
