
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060102
// Wed Dec 20 21:02:26 ART 2006
//----------------------------------------------------

package javax.swing.text.html.parser;

/** CUP generated interface containing symbol constants. */
interface ParserSym {
  /* terminals */
  public static final int TAG_CLOSE = 4;
  public static final int TAG_COMM_CLOSE = 10;
  public static final int EOFTK = 25;
  public static final int TAG_SLASH_CLOSE = 9;
  public static final int ATTR_NAME = 17;
  public static final int LEXERR = 24;
  public static final int MUDECL = 22;
  public static final int TAG_OPEN = 3;
  public static final int COMM = 8;
  public static final int ATTRVAL_NMTK = 19;
  public static final int ATTRVAL_NUM = 21;
  public static final int EMPTY_TAG = 11;
  public static final int MUDECL_CONTENT = 23;
  public static final int LEXERR_EXPECTED_TAG_NAME = 27;
  public static final int EQUALS = 5;
  public static final int END_TAG_NAME = 13;
  public static final int DQM = 6;
  public static final int EOF = 0;
  public static final int TAG_NAME = 14;
  public static final int error = 1;
  public static final int SYNC = 2;
  public static final int ATTRVAL_NUMTK = 20;
  public static final int TEXT = 16;
  public static final int SQM = 7;
  public static final int EOF_LITERAL = 26;
  public static final int COMM_CONTENT = 15;
  public static final int ATTRVAL_LIT = 18;
  public static final int TAG_OPEN_EXM = 12;
}

