/* Copyright 2006 The Apache Software Foundation or its licensors, as applicable
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_platform_IMemorySystem */

#ifndef _Included_com_ibm_platform_IMemorySystem
#define _Included_com_ibm_platform_IMemorySystem
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibm_platform_IMemorySystem_MMAP_READ_ONLY
#define com_ibm_platform_IMemorySystem_MMAP_READ_ONLY 1L
#undef com_ibm_platform_IMemorySystem_MMAP_READ_WRITE
#define com_ibm_platform_IMemorySystem_MMAP_READ_WRITE 2L
#undef com_ibm_platform_IMemorySystem_MMAP_WRITE_COPY
#define com_ibm_platform_IMemorySystem_MMAP_WRITE_COPY 4L
#ifdef __cplusplus
}
#endif
#endif
