com/ibm/lang/management/ClassLoadingMXBeanImplTest.java
com/ibm/lang/management/CompilationMXBeanImplTest.java
com/ibm/lang/management/DynamicMXBeanImplTest.java
com/ibm/lang/management/GarbageCollectorMXBeanImplTest.java
com/ibm/lang/management/LoggingMXBeanImplTest.java
com/ibm/lang/management/MemoryManagerImplTest.java
com/ibm/lang/management/MemoryMXBeanImplTest.java
com/ibm/lang/management/MemoryPoolMXBeanImplTest.java
com/ibm/lang/management/MultiInstanceDynamicMXBeanImplTest.java
com/ibm/lang/management/RuntimeMXBeanImplTest.java
com/ibm/lang/management/SingleInstanceDynamicMXBeanImplTest.java
com/ibm/lang/management/ThreadInfoTest.java
com/ibm/lang/management/ThreadMXBeanImplTest.java

tests/java/lang/management/ClassLoadingMXBeanTest.java
tests/java/lang/management/CompilationMXBeanTest.java
tests/java/lang/management/GarbageCollectorMXBeanTest.java
tests/java/lang/management/LoggingMXBeanTest.java
tests/java/lang/management/ManagementFactoryTest.java
tests/java/lang/management/MemoryManagerMXBeanTest.java
tests/java/lang/management/MemoryMXBeanTest.java
tests/java/lang/management/MemoryPoolMXBeanTest.java
tests/java/lang/management/MemoryUsageTest.java
tests/java/lang/management/RuntimeMXBeanTest.java
tests/java/lang/management/ThreadMXBeanTest.java

tests/java/util/logging/LoggingMXBeanTest.java