HYTEXT_0.1 {
	global :		
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1close;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1countRuns;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1getDirection;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1getLength;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1getLevels;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1getParaLevel;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1getRun;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1open;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1reorderVisual;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1setLine;
		Java_org_apache_harmony_text_BidiWrapper_ubidi_1setPara;
	local : *;
};
