HYMATH_0.1 {
	global :
		Java_org_apache_harmony_luni_util_FloatingPointParser_parseDblImpl;
		Java_org_apache_harmony_luni_util_FloatingPointParser_parseFltImpl;
		Java_org_apache_harmony_math_util_BigInteger_addImpl;
		Java_org_apache_harmony_math_util_BigInteger_compImpl;
		Java_org_apache_harmony_math_util_BigInteger_divImpl;
		Java_org_apache_harmony_math_util_BigInteger_mulImpl;
		Java_org_apache_harmony_math_util_BigInteger_negImpl;
		Java_org_apache_harmony_math_util_BigInteger_remImpl;
		Java_org_apache_harmony_math_util_BigInteger_shlImpl;
		Java_org_apache_harmony_math_util_BigInteger_subImpl;
		Java_org_apache_harmony_luni_util_NumberConverter_bigIntDigitGeneratorInstImpl;
		JNI_OnLoad;
		JNI_OnUnload;
	local : *;
};
