/* 
 *  Licensed to the Apache Software Foundation (ASF) under one or more 
 *  contributor license agreements.  See the NOTICE file distributed with 
 *  this work for additional information regarding copyright ownership. 
 *  The ASF licenses this file to You under the Apache License, Version 2.0 
 *  (the "License"); you may not use this file except in compliance with 
 *  the License.  You may obtain a copy of the License at 
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0 
 * 
 *  Unless required by applicable law or agreed to in writing, software 
 *  distributed under the License is distributed on an "AS IS" BASIS, 
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *  See the License for the specific language governing permissions and 
 *  limitations under the License. 
 */
/* Generated By:JavaCC: Do not edit this line. FilterParserConstants.java */

package org.apache.harmony.jndi.provider.ldap.parser;

public interface FilterParserConstants {

  int EOF = 0;
  int COLON_DN = 1;
  int HEX_CHAR = 2;
  int NOHEX_CHAR = 3;
  int LPARENT = 4;
  int RPARENT = 5;
  int LBRACE = 6;
  int RBRACE = 7;
  int AND = 8;
  int OR = 9;
  int NOT = 10;
  int ZERO = 11;
  int COLON = 12;
  int EQUAL = 13;
  int LESS = 14;
  int GREATER = 15;
  int APPROX = 16;
  int ASTERISK = 17;
  int DIGIT = 18;
  int HYPHEN = 19;
  int PERIOD = 20;
  int BACKSLASH = 21;
  int SEMI = 22;
  int CHAR = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\":dn\"",
    "<HEX_CHAR>",
    "<NOHEX_CHAR>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"0\"",
    "\":\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"~\"",
    "\"*\"",
    "<DIGIT>",
    "\"-\"",
    "\".\"",
    "\"\\\\\"",
    "\";\"",
    "<CHAR>",
    "\"\\n\"",
  };

}
