/* 
 *  Licensed to the Apache Software Foundation (ASF) under one or more 
 *  contributor license agreements.  See the NOTICE file distributed with 
 *  this work for additional information regarding copyright ownership. 
 *  The ASF licenses this file to You under the Apache License, Version 2.0 
 *  (the "License"); you may not use this file except in compliance with 
 *  the License.  You may obtain a copy of the License at 
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0 
 * 
 *  Unless required by applicable law or agreed to in writing, software 
 *  distributed under the License is distributed on an "AS IS" BASIS, 
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *  See the License for the specific language governing permissions and 
 *  limitations under the License. 
 */
/* Generated By:JavaCC: Do not edit this line. LdapUrlParserConstants.java */

package org.apache.harmony.jndi.provider.ldap.parser;

public interface LdapUrlParserConstants {

  int EOF = 0;
  int SCHEME = 1;
  int PRE_XTOKEN = 2;
  int SCOPE = 3;
  int COMMA = 4;
  int QUESTION_MARK = 5;
  int SLASH = 6;
  int PERCENT = 7;
  int COLON = 8;
  int PERIOD = 9;
  int EXCLAM_MARK = 10;
  int EQUAL = 11;
  int HEX_CHAR = 12;
  int NOHEX_CHAR = 13;
  int DIGIT = 14;
  int ZERO = 15;
  int CHAR = 16;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<SCHEME>",
    "<PRE_XTOKEN>",
    "<SCOPE>",
    "\",\"",
    "\"?\"",
    "\"/\"",
    "\"%\"",
    "\":\"",
    "\".\"",
    "\"!\"",
    "\"=\"",
    "<HEX_CHAR>",
    "<NOHEX_CHAR>",
    "<DIGIT>",
    "\"0\"",
    "<CHAR>",
    "\"\\n\"",
  };

}
