/*
 *  Copyright 2005 - 2006 The Apache Software Software Foundation or its licensors, as applicable.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * @author Alexey A. Petrenko
 * @version $Revision$
 */
/*
 * THE FILE HAS BEEN AUTOGENERATED BY INTEL IJH TOOL.
 * Please be aware that all changes made to this file manually
 * will be overwritten by the tool if it runs again.
 */

#include <jni.h>


/* Header for class org.apache.harmony.awt.gl.render.NativeImageBlitter */

#ifndef _ORG_APACHE_HARMONY_AWT_GL_RENDER_NATIVEIMAGEBLITTER_H
#define _ORG_APACHE_HARMONY_AWT_GL_RENDER_NATIVEIMAGEBLITTER_H

#ifdef __cplusplus
extern "C" {
#endif


/* Native methods */

/*
 * Method: org.apache.harmony.awt.gl.render.NativeImageBlitter.xor(IIJLjava/lang/Object;IIJLjava/lang/Object;III[I)V
 */
JNIEXPORT void JNICALL
Java_org_apache_harmony_awt_gl_render_NativeImageBlitter_xor(JNIEnv *, jobject, 
    jint, jint, jlong, jobject, jint, jint, jlong, jobject, jint, jint, jint, jintArray);

/*
 * Method: org.apache.harmony.awt.gl.render.NativeImageBlitter.blt(IIJLjava/lang/Object;IIJLjava/lang/Object;IIIF[I)V
 */
JNIEXPORT void JNICALL
Java_org_apache_harmony_awt_gl_render_NativeImageBlitter_blt(JNIEnv *, jobject, 
    jint, jint, jlong, jobject, jint, jint, jlong, jobject, jint, jint, jint, jfloat, jintArray);

/*
 * Method: org.apache.harmony.awt.gl.render.NativeImageBlitter.bltBG(IIJLjava/lang/Object;IIJLjava/lang/Object;IIIIF[I)V
 */
JNIEXPORT void JNICALL
Java_org_apache_harmony_awt_gl_render_NativeImageBlitter_bltBG(JNIEnv *, jobject, 
    jint, jint, jlong, jobject, jint, jint, jlong, jobject, jint, jint, jint, jint, jfloat, jintArray);


#ifdef __cplusplus
}
#endif

#endif /* _ORG_APACHE_HARMONY_AWT_GL_RENDER_NATIVEIMAGEBLITTER_H */

